# Matrices and Matrix Operations

This function introduces various ways to create
matrices and how to use them in TensorFlow

In [1]:
import numpy as np
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from tensorflow.python.framework import ops
ops.reset_default_graph()

Instructions for updating:
non-resource variables are not supported in the long term


Start a graph session

In [2]:
sess = tf.Session()

### Declaring matrices

Identity Matrix:

In [3]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2x3 random norm matrix:

In [4]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[ 1.4676073   0.31920636 -1.2420403 ]
 [ 0.33100408  0.72369456 -0.04735705]]


2x3 constant matrix:

In [5]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


3x2 random uniform matrix:

In [6]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[0.35272336 0.0859412 ]
 [0.07688463 0.98010886]
 [0.3937837  0.43654835]]


Create matrix from np array:

In [9]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### Matrix Operations

Matrix addition/subtraction:

In [10]:
print(sess.run(A+B))
print(sess.run(B-B))

[[4.7448044 5.1968455 6.9891815]
 [6.1111426 5.2149725 4.8160415]]
[[0. 0. 0.]
 [0. 0. 0.]]


Matrix Multiplication:

In [11]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


Matrix Transpose:

In [12]:
print(sess.run(tf.transpose(C)))

[[0.20776379 0.37206912 0.25386512]
 [0.91686606 0.94667494 0.71231794]]


Matrix Determinant:

In [13]:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


Matrix Inverse:

In [14]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


Cholesky Decomposition:

In [15]:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Eigenvalues and Eigenvectors:  We use `tf.self_adjoint_eig()` function, which returns two objects, first one is an array of eigenvalues, the second is a matrix of the eigenvectors.

In [16]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]
